/**
 * OpenBlob production Deno server.
 *
 * - Serves static assets from `build/client/`.
 * - Delegates everything else to the React Router request handler from
 *   `build/server/index.js`.
 * - Registers a `Deno.cron` that bundles pending microblobs in-process
 *   (no HTTP roundtrip back to ourselves).
 *
 * Run with:
 *   deno task build && deno task start
 *
 * For development, run `deno task dev` (which uses `react-router dev`).
 */

import { createRequestHandler, type ServerBuild } from "react-router";

import { registerBundlerCron } from "./app/lib/bundler-cron.server.ts";

// The React Router build output is generated by `deno task build` into
// `build/server/index.js`. We load it via a dynamic import + URL so neither
// TypeScript nor `deno check` tries to resolve it at type-check time — that
// way `deno task typecheck` works on a fresh clone before the first build.
//
// The import is deferred until the first HTTP request so that on Deno Deploy
// the cron isolate (which evaluates this same file just to register the cron
// callback) does not pay to parse + evaluate the entire React Router server
// bundle every time it cold-starts.
const buildUrl = new URL("./build/server/index.js", import.meta.url).href;

type Handler = ReturnType<typeof createRequestHandler>;
let handlerPromise: Promise<Handler> | null = null;

function getHandler(): Promise<Handler> {
  if (!handlerPromise) {
    handlerPromise = (async () => {
      const build = (await import(buildUrl)) as ServerBuild;
      return createRequestHandler(build, "production");
    })();
  }
  return handlerPromise;
}

const clientRoot = new URL("./build/client/", import.meta.url);

const ONE_YEAR = 60 * 60 * 24 * 365;

async function tryServeStatic(url: URL): Promise<Response | null> {
  if (url.pathname === "/" || url.pathname.endsWith("/")) return null;
  // Disallow path traversal.
  if (url.pathname.includes("..")) return null;

  const filePath = new URL(`.${url.pathname}`, clientRoot);
  try {
    const stat = await Deno.stat(filePath);
    if (!stat.isFile) return null;
  } catch {
    return null;
  }

  const file = await Deno.open(filePath, { read: true });
  const headers = new Headers();
  headers.set("Content-Type", contentTypeFor(url.pathname));
  // Vite emits hashed asset filenames; mark them long-lived.
  if (url.pathname.startsWith("/assets/")) {
    headers.set("Cache-Control", `public, max-age=${ONE_YEAR}, immutable`);
  } else {
    headers.set("Cache-Control", "public, max-age=3600");
  }
  return new Response(file.readable, { headers });
}

function contentTypeFor(pathname: string): string {
  if (pathname.endsWith(".js") || pathname.endsWith(".mjs")) return "text/javascript; charset=utf-8";
  if (pathname.endsWith(".css")) return "text/css; charset=utf-8";
  if (pathname.endsWith(".html")) return "text/html; charset=utf-8";
  if (pathname.endsWith(".json")) return "application/json";
  if (pathname.endsWith(".svg")) return "image/svg+xml";
  if (pathname.endsWith(".png")) return "image/png";
  if (pathname.endsWith(".jpg") || pathname.endsWith(".jpeg")) return "image/jpeg";
  if (pathname.endsWith(".webp")) return "image/webp";
  if (pathname.endsWith(".woff2")) return "font/woff2";
  if (pathname.endsWith(".ico")) return "image/x-icon";
  return "application/octet-stream";
}

Deno.serve(async (request) => {
  const url = new URL(request.url);
  const staticResponse = await tryServeStatic(url);
  if (staticResponse) return staticResponse;
  const handler = await getHandler();
  return handler(request);
});

// Bundle pending microblobs in-process. On Deno Deploy this runs in a
// dedicated cron isolate, but it still has the same Deno KV view as the
// request isolates, so calling KV directly is sufficient — no need to
// fetch back into ourselves over HTTP.
registerBundlerCron();
